### ISSUE TITLE
エディタに[Git送信]ボタンを追加

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/konawiki3#13]
普段から、テキストエディタの代わりにKonaWiki3を使っていて、頻繁に保存と表示を行ったり来たりしています。

一時保存機能の実装 #9 でlocalStorageにだけ保存するようにしてもらいましたが、、、しばらく執筆の仕事に使ってみたところ、Ctrl + Sでファイルへ保存し、Git pushはせずファイル保存だけやって欲しく感じました。

そのため、保存キーは以下のように三種類作ろうと思います。

- 保存 --- ファイルへ保存
- 保存 & 表示 --- ファイルへ保存して更新
- Git 送信 --- git commit & git push

**Comment by massongit** [comment]
`Git送信` だと「Gitって何？」となるユーザーもいるかと思うので、Gitという単語を使わずに表現する ( `編集履歴を残して保存` とか) 方が良いかもしれないですね。

**Comment by kujirahand** [comment]
それは良い考えですね。そうしましょう！
