### ISSUE TITLE
一時保存機能の実装

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/konawiki3#9]
現行では、「保存」ボタンを押したとき、改行による自動時にも、git pushが走るので、非常に重たい印象。

そこで、「一時保存」ボタンを押した時、自動保存時には、JavaScriptでlocalStorageへ保存するようにし、「保存と反映」ボタンを押した時に、Git commit & push が走るようにする。

**Comment by massongit** [comment]
改行による自動保存の際には元々localstorageに保存するようになっているようなので (以下参照)、SaveボタンをTemporary Saveに置き換えて、localStorageへ保存するようにする形ですかね。

https://github.com/kujirahand/konawiki3/blob/38bd5760e569a44f8068fbbd7fc42dcfd8120fd7/kona3engine/resource/edit.js#L24-L28
